# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget


class Ui_Form(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        # drop down button
        self.dropDownPushButton = DropDownPushButton('Email', self, FIF.MAIL)
        self.dropDownToolButton = DropDownToolButton(FIF.MAIL, self)
        self.menu = RoundMenu(parent=self)
        self.menu.addAction(QAction(FIF.SEND_FILL.icon(), 'Send'))
        self.menu.addAction(QAction(FIF.SAVE.icon(), 'Save'))
        self.dropDownPushButton.setMenu(self.menu)
        self.dropDownToolButton.setMenu(self.menu)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 668)
        self.pushButton = PushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(170, 230, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.setWindowFlags(Qt.FramelessWindowHint)  # 去边框
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))


from qfluentwidgets import PushButton

if __name__ == '__main__':
    # enable dpi scale
    QApplication.setHighDpiScaleFactorRoundingPolicy(
        Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)

    app = QApplication(sys.argv)
    w = Ui_Form()
    w.show()
    app.exec_()
